[pytest]
# 测试文件匹配规则
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# 测试目录
testpaths = case

# 默认命令行参数（核心配置）
addopts = -vs --alluredir=./allure_results --clean-alluredir

# 标记定义（配合 pytest-dependency 等插件使用）
markers =
    dependency: 标记测试用例依赖关系
    smoke: 冒烟测试
    regression: 回归测试
    critical: 核心用例


# 超时设置（需安装 pytest-timeout）
timeout = 300
